# General {{{1
title: "Clássico, tradicional, eclético: nacionalismo e cosmopolitismo na cidade industrial"
email: palazzo@unb.br
description: >-
  Discursos arquitetônicos produzidos de c. 1860 a 1930,
  com ênfase na formação dos campos teóricos brasileiros
  compreendidos numa abordagem global.
baseurl: "/arqtrad"
url: "https://dmcpatrimonio.github.io"
lang: pt
twitter_username: p3palazzo
github_username:  dmcpatrimonio
open_graph: https://repository-images.githubusercontent.com/224453298/09a3bd80-60be-11ea-83cb-4b22bffcf270

# Content {{{1
collections: # {{{2
  creativework:
    output   : true
    permalink: /:collection/:name
  event:
    output   : true
    permalink: /:collection/:name
  organization:
    output   : true
    permalink: /:collection/:name
  person:
    output   : true
    permalink: /:collection/:name
  place:
    output   : true
    permalink: /:collection/:name
  thing:
    output   : true
    permalink: /:collection/:name

defaults: # {{{2
  -
    scope:
      path      : ""
      type      : "person"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Person"
      class     : "Agent"
  -
    scope:
      path      : ""
      type      : "organization"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Organization"
      class     : "AgentClass"
  -
    scope:
      path      : ""
      type      : "event"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Event"
      type      : "Event"
  -
    scope:
      path      : ""
      type      : "place"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Place"
      class     : "Location"
  -
    scope:
      path      : ""
      type      : "creativework"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/CreativeWork"
      type      : "PhysicalObject"
  -
    scope:
      path      : ""
      type      : "thing"
    values:
      layout    : "thing"
      itemtype  : "http://schema.org/Thing"

# Build settings {{{1
theme: minima # {{{2
minima:
  date_format : "%e %B %Y"
  social_links:
    twitter   : https://twitter.com/p3palazzo
    github    : https://github.com/dmcpatrimonio/arqtrad
    instagram : https://instagram.com/arqtrad
header_pages:
  - atual.md
  - ppgfau-projeto.md

plugins: # {{{2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Other build parameters {{{2
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: true
  header_offset: 1
  parse_block_html: true
  parse_span_html: true
  transliterated_header_ids: true
relative_links:
  enabled: true
  collections: true
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# vim: set foldmethod=marker :
