name: Website

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert from Pandoc-Markdown to GFM
      run: make pandoc
    - name: Upload web pages
      uses: actions/upload-artifact@v2
      with:
        name: pages
        path: 'tmp/*.md'
  build:
    runs-on: ubuntu-latest
    needs: pandoc
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        fetch-depth: 0
    - name: Merge changes from active branch
      run: |
        git config --local user.email "runner@github.com"
        git config --local user.name  "$GITHUB_ACTOR"
        git merge -s ours ${{ env.GITHUB_REF }}
    - name: Update pages
      uses: actions/download-artifact@v2
      with:
        name: pages
        path: ${{ github.workspace }}/
    - name: Test Jekyll site build
      run: make build
  gh-pages:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.repository == 'dmcpatrimonio/arqtrad'
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        fetch-depth: 0
    - name: Merge changes from master branch
      run: |
        git config --local user.email "runner@github.com"
        git config --local user.name  "$GITHUB_ACTOR"
        git fetch --all
        git merge origin/master
    - name: Update pages
      uses: actions/download-artifact@v2
      with:
        name: pages
        path: ${{ github.workspace }}/
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "runner@github.com"
        git config --local user.name  "$GITHUB_ACTOR"
        git add .
        git commit -m "${{ env.commit_message }}" -a || git status
        git pull
        git push
